"""Generate LaTeX/CSV/JSON tables for the paper.

Outputs are written to ./generated by default:
  - theorem_representative.tex / .csv / .json
  - qubo_structure.tex / .csv / .json
  - robustness_summary.tex / .csv / .json
  - snark_benchmarks.tex / .csv / .json    (Table 7: snark suite)

Run from repo root with:
    python scripts/generate_paper_tables.py
"""

from __future__ import annotations

import csv
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from nzflow_qubo import (  # noqa: E402
    build_hamiltonian,
    count_flows,
    enumerate_flows,
    encode_flow,
    qubo_stats,
    solve_exact,
)
from nzflow_qubo.benchmarks import (  # noqa: E402
    K,
    K_bipartite,
    cube,
    petersen,
    theta_3,
    K4_doubled,
    triangular_prism,
)
from nzflow_qubo.graph import Orientation, Multigraph  # noqa: E402
from nzflow_qubo.snarks import SNARK_SUITE, girth, is_snark  # noqa: E402

OUTDIR = ROOT / "generated"
OUTDIR.mkdir(exist_ok=True)
LATEX_NL = r"\\"


def latex_graph_name(name: str) -> str:
    mapping = {
        "K_3": r"$K_3$",
        "K_4": r"$K_4$",
        "K_{3,3}": r"$K_{3,3}$",
        "Theta_3": r"$\Theta_3$",
        "Q_3": r"$Q_3$",
        "K_4 doubled": r"$K_4$ doubled",
    }
    return mapping.get(name, name)


def n_components(G: Multigraph) -> int:
    parent = list(range(G.n))

    def find(x: int) -> int:
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    def union(a: int, b: int) -> None:
        ra, rb = find(a), find(b)
        if ra != rb:
            parent[ra] = rb

    for u, v in G.edges:
        union(u, v)
    return len({find(x) for x in range(G.n)})


def cycle_rank(G: Multigraph) -> int:
    return G.m - G.n + n_components(G)


def dynamic_range_from_quadratic(spec) -> tuple[float, float, float | None]:
    quad_abs = sorted(abs(float(v)) for v in spec.bqm.quadratic.values() if abs(float(v)) > 1e-12)
    if not quad_abs:
        return 0.0, 0.0, None
    mn = quad_abs[0]
    mx = quad_abs[-1]
    return mn, mx, (mx / mn if mn > 0 else None)


def distinct_zero_energy_flow_count(spec) -> int | None:
    if spec.n_vars > 18:
        return None
    result = solve_exact(spec)
    flows = {tuple(f[e] for e in range(spec.G.m)) for f in result.zero_energy_flows()}
    return len(flows)


def write_csv_json(prefix: str, rows: list[dict[str, Any]]) -> None:
    csv_path = OUTDIR / f"{prefix}.csv"
    json_path = OUTDIR / f"{prefix}.json"
    with csv_path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)
    json_path.write_text(json.dumps(rows, indent=2))


def generate_theorem_representative() -> list[dict[str, Any]]:
    cases = [
        ("K_3", K(3), 2),
        ("K_4", K(4), 3),
        ("K_4", K(4), 4),
        ("K_{3,3}", K_bipartite(3, 3), 3),
        ("Theta_3", theta_3(), 3),
        ("Triangular prism", triangular_prism(), 3),
        ("Petersen", petersen(), 3),
        ("Petersen", petersen(), 4),
        ("Petersen", petersen(), 5),
        ("K_4 doubled", K4_doubled(), 3),
        ("Q_3", cube(), 5),
    ]
    rows: list[dict[str, Any]] = []
    for name, G, k in cases:
        spec = build_hamiltonian(G, k)
        flows = enumerate_flows(G, k)
        c1 = all(abs(spec.bqm.energy(encode_flow(spec, f))) < 1e-9 for f in flows)
        rows.append(
            {
                "graph": name,
                "k": k,
                "edges": G.m,
                "beta": cycle_rank(G),
                "flows": len(flows),
                "c1": c1,
                "n_vars": spec.n_vars,
                "zero_energy_states_exact": distinct_zero_energy_flow_count(spec),
            }
        )
    return rows


def write_theorem_representative(rows: list[dict[str, Any]]) -> None:
    write_csv_json("theorem_representative", rows)
    tex_path = OUTDIR / "theorem_representative.tex"
    lines = [
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\caption{Representative exact flow counts and threshold instances. The flow counts are exact and use the cycle-space extension enumerator. Column C1 records whether every exact flow encoded to zero energy under $H_{\mathrm{mod},k}$. The exact zero-energy-state count is reported when the BQM is small enough for exhaustive ground-state enumeration.}",
        r"\label{tab:theorem-representative}",
        r"\begin{tabular}{lrrrrrrr}",
        r"\hline",
        f"Graph & $k$ & $|E|$ & $\\beta$ & \\#flows & C1 & vars & exact zero-E {LATEX_NL}",
        r"\hline",
    ]
    for row in rows:
        ztxt = "--" if row["zero_energy_states_exact"] is None else str(row["zero_energy_states_exact"])
        c1txt = "--" if row["flows"] == 0 else ("yes" if row["c1"] else "FAIL")
        lines.append(
            f"{latex_graph_name(row['graph'])} & {row['k']} & {row['edges']} & {row['beta']} & {row['flows']} & "
            f"{c1txt} & {row['n_vars']} & {ztxt} {LATEX_NL}"
        )
    lines.extend([r"\hline", r"\end{tabular}", r"\end{table}"])
    tex_path.write_text("\n".join(lines) + "\n")


def generate_qubo_structure() -> list[dict[str, Any]]:
    cases = [
        ("Theta_3", theta_3(), 3),
        ("K_4", K(4), 4),
        ("K_{3,3}", K_bipartite(3, 3), 3),
        ("Triangular prism", triangular_prism(), 3),
        ("K_4 doubled", K4_doubled(), 3),
        ("Petersen", petersen(), 4),
        ("Petersen", petersen(), 5),
        ("Q_3", cube(), 5),
    ]
    rows: list[dict[str, Any]] = []
    for name, G, k in cases:
        spec = build_hamiltonian(G, k)
        s = qubo_stats(spec)
        qmin, qmax, ratio = dynamic_range_from_quadratic(spec)
        rows.append(
            {
                "graph": name,
                "k": k,
                "n_vars": s["n_vars"],
                "n_quadratic": s["n_quadratic"],
                "density": s["density"],
                "offset": s["offset"],
                "linear_min": s["linear_min"],
                "linear_max": s["linear_max"],
                "quadratic_min": s["quadratic_min"],
                "quadratic_max": s["quadratic_max"],
                "min_nonzero_abs_Q": qmin,
                "max_abs_Q": qmax,
                "dynamic_range": ratio,
            }
        )
    return rows


def write_qubo_structure(rows: list[dict[str, Any]]) -> None:
    write_csv_json("qubo_structure", rows)
    tex_path = OUTDIR / "qubo_structure.tex"
    lines = [
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\caption{Structural statistics of the binary quadratic models $H_{\mathrm{mod},k}$ at $A=B=1$. Density is the fraction of present quadratic couplers among all possible couplers on the logical graph. The final column reports $\max|Q|/\min\{|Q_{ij}|:Q_{ij}\neq 0\}$.}",
        r"\label{tab:qubo-structure}",
        r"\begin{tabular}{lrrrrrrr}",
        r"\hline",
        f"Graph & $k$ & vars & couplers & density & offset & $\\max |Q|$ & dyn. range {LATEX_NL}",
        r"\hline",
    ]
    for row in rows:
        dr = "--" if row["dynamic_range"] is None else f"{row['dynamic_range']:.1f}:1"
        lines.append(
            f"{latex_graph_name(row['graph'])} & {row['k']} & {row['n_vars']} & {row['n_quadratic']} & {row['density']:.3f} & "
            f"{row['offset']:.0f} & {row['max_abs_Q']:.0f} & {dr} {LATEX_NL}"
        )
    lines.extend([r"\hline", r"\end{tabular}", r"\end{table}"])
    tex_path.write_text("\n".join(lines) + "\n")


def generate_snark_benchmarks() -> list[dict[str, Any]]:
    """Reproduce Table 7 of the paper: the snark benchmark suite.

    For each graph in SNARK_SUITE (Petersen, J_5, J_7) and each
    k in {3, 4, 5}, this function:

      1. constructs the graph and verifies (n, m) against the suite tripwire;
      2. verifies snark status via is_snark() with 3-edge-colorability check;
      3. computes the cycle rank beta = |E| - |V| + c(G);
      4. attempts to count nowhere-zero Z_k flows when the spanning-tree
         enumeration cost (k-1)^beta is within the paper's budget 5e6;
         reports None when outside budget (rendered as '--' in the table);
      5. builds H_{mod,k} and reports vars and quadratic couplers.

    For snarks (cubic, non-3-edge-colorable), k=3 and k=4 are no-instances
    by the equivalence of nowhere-zero 4-flows with 3-edge-colorings on
    cubic graphs (and any nowhere-zero 3-flow induces a 4-flow); the C1
    column is therefore vacuous for those rows (no flows to encode).

    Raises RuntimeError if any suite entry fails the snark check at
    runtime, or if a counted k=3 or k=4 flow count is nonzero (would
    contradict the snark property).
    """
    SNARK_BUDGET = 5_000_000   # paper's snark-table enumeration budget

    rows: list[dict[str, Any]] = []
    for name, builder, n_exp, m_exp, do_color_check in SNARK_SUITE:
        G = builder()

        # Tripwire: edge/vertex count must match what the suite advertises.
        if G.n != n_exp or G.m != m_exp:
            raise RuntimeError(
                f"SNARK_SUITE tripwire failed for {name!r}: "
                f"expected (n={n_exp}, m={m_exp}), got (n={G.n}, m={G.m})"
            )

        # Audit: this entry must satisfy the snark predicate.
        if not is_snark(G, check_colorable=do_color_check):
            raise RuntimeError(
                f"SNARK_SUITE entry {name!r} failed is_snark() at table "
                f"generation time. Refusing to write a row claiming snark "
                f"status. Check nzflow_qubo/snarks.py construction."
            )

        beta = G.m - G.n + n_components(G)

        for k in (3, 4, 5):
            spec = build_hamiltonian(G, k)
            stats = qubo_stats(spec)

            enum_cost = (k - 1) ** beta
            if enum_cost <= SNARK_BUDGET:
                flow_count = count_flows(G, k)
            else:
                flow_count = None

            # Sanity check: for snarks, k=3 and k=4 must yield 0 flows
            # whenever the count is reported (snark property: phi >= 5).
            if k in (3, 4) and flow_count is not None and flow_count != 0:
                raise RuntimeError(
                    f"SNARK_SUITE entry {name!r}: count_flows at k={k} returned "
                    f"{flow_count}, but snarks have phi >= 5 so 0 is expected. "
                    f"This indicates either a snark mis-identification or a "
                    f"bug in count_flows."
                )

            # C1 column: 'yes' if there is at least one enumerated flow that
            # encodes to H=0; '--' if there are no enumerated flows to check
            # (vacuous) or the enumeration was outside budget.
            if flow_count is not None and flow_count > 0:
                # Verify forward encoding on every enumerated flow.
                c1_ok = all(
                    spec.bqm.energy(encode_flow(spec, f)) == 0
                    for f in enumerate_flows(G, k)
                )
                c1_label = "yes" if c1_ok else "FAIL"
            else:
                c1_label = "--"

            rows.append({
                "graph": name,
                "k": k,
                "n_vertices": G.n,
                "n_edges": G.m,
                "beta": beta,
                "flow_count": flow_count,   # None means '--' in the table
                "C1": c1_label,
                "vars": stats["n_vars"],
                "couplers": stats["n_quadratic"],
            })
    return rows


def write_snark_benchmarks(rows: list[dict[str, Any]]) -> None:
    write_csv_json("snark_benchmarks", rows)
    tex_path = OUTDIR / "snark_benchmarks.tex"

    # Caption matches Table 7 of the published paper verbatim.
    caption = (
        r"Snark benchmarks. The Petersen graph and the Isaacs flower "
        r"snarks $J_5$ (20 vertices) and $J_7$ (28 vertices) are connected, "
        r"bridgeless, cubic, girth at least $5$, and not $3$-edge-colorable; "
        r"\texttt{flower\_snark(5)} is verified isomorphic to SageMath's canonical "
        r"\texttt{graphs.FlowerSnark()}. Since for cubic graphs "
        r"$3$-edge-colorability is equivalent to admitting a nowhere-zero "
        r"$4$-flow, and a nowhere-zero $3$-flow would imply a nowhere-zero "
        r"$4$-flow, the $k\in\{3,4\}$ snark rows are no-instances. The $k=5$ "
        r"rows probe the near-threshold case: Petersen and $J_5$ are confirmed "
        r"yes-instances by the enumerated counts in the table, while the $J_7,k=5$ "
        r"enumeration is outside the stated budget. The column \#flows is the exact cycle-space enumerator count when the "
        r"enumeration is within budget; a dash (--) in the \#flows column marks "
        r"configurations whose enumeration $(k-1)^\beta$ exceeds the budget "
        r"$5\times 10^6$. The C1 column is marked yes when enumerated flows were "
        r"checked to encode to $H_{\mathrm{mod},k}=0$, and is marked -- when C1 is "
        r"vacuous or outside budget. The structural columns are exact for every "
        r"row. For $J_7,k=4$, the no-instance conclusion follows from "
        r"non-$3$-edge-colorability rather than from enumeration."
    )

    lines = [
        r"\begin{table}[H]",
        r"\centering",
        r"\small",
        r"\begin{tabular}{lrrrrrrrr}",
        r"\hline",
        rf"Graph & $k$ & $n$ & $|E|$ & $\beta$ & \#flows & C1 & vars & couplers {LATEX_NL}",
        r"\hline",
    ]
    for row in rows:
        flows_cell = "--" if row["flow_count"] is None else str(row["flow_count"])
        lines.append(
            f"{latex_graph_name(row['graph'])} & {row['k']} & "
            f"{row['n_vertices']} & {row['n_edges']} & {row['beta']} & "
            f"{flows_cell} & {row['C1']} & {row['vars']} & {row['couplers']} {LATEX_NL}"
        )
    lines.extend([
        r"\hline",
        r"\end{tabular}",
        rf"\caption{{{caption}}}",
        r"\label{tab:snark-benchmarks}",
        r"\end{table}",
    ])
    tex_path.write_text("\n".join(lines) + "\n")


def generate_robustness_summary() -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []

    G = K(4)
    expected = count_flows(G, 4)
    ok = all(count_flows(G, 4, D=Orientation.from_bitmask(G, mask)) == expected for mask in range(1 << G.m))
    rows.append({"sweep": "orientations", "graph": "K_4", "k": 4, "cases": 1 << G.m, "invariant": expected, "status": ok})

    G = K_bipartite(3, 3)
    expected = count_flows(G, 3)
    ok = all(count_flows(G, 3, D=Orientation.from_bitmask(G, mask)) == expected for mask in range(1 << G.m))
    rows.append({"sweep": "orientations", "graph": "K_{3,3}", "k": 3, "cases": 1 << G.m, "invariant": expected, "status": ok})

    G = theta_3()
    expected = count_flows(G, 3)
    ok = all(count_flows(G, 3, D=Orientation.from_bitmask(G, mask)) == expected for mask in range(1 << G.m))
    rows.append({"sweep": "orientations", "graph": "Theta_3", "k": 3, "cases": 1 << G.m, "invariant": expected, "status": ok})

    G = K_bipartite(3, 3)
    expected = count_flows(G, 3, root=0)
    ok = all(count_flows(G, 3, root=r) == expected for r in range(G.n))
    rows.append({"sweep": "roots", "graph": "K_{3,3}", "k": 3, "cases": G.n, "invariant": expected, "status": ok})

    G = petersen()
    expected = count_flows(G, 5, root=0)
    ok = all(count_flows(G, 5, root=r) == expected for r in range(G.n))
    rows.append({"sweep": "roots", "graph": "Petersen", "k": 5, "cases": G.n, "invariant": expected, "status": ok})

    weight_pairs = [(1.0, 1.0), (10.0, 1.0), (1.0, 10.0), (0.1, 1.0), (1.0, 0.1), (5.0, 0.5)]
    G = theta_3()
    expected = count_flows(G, 4)
    ok = True
    for A, B in weight_pairs:
        spec = build_hamiltonian(G, 4, A=A, B=B)
        if distinct_zero_energy_flow_count(spec) != expected:
            ok = False
            break
    rows.append({"sweep": "weights", "graph": "Theta_3", "k": 4, "cases": len(weight_pairs), "invariant": expected, "status": ok})
    return rows


def write_robustness_summary(rows: list[dict[str, Any]]) -> None:
    write_csv_json("robustness_summary", rows)
    tex_path = OUTDIR / "robustness_summary.tex"
    lines = [
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\caption{Exact robustness sweeps. Each sweep preserves the exact flow count, consistent with the theorem-level invariance of $H_{\mathrm{mod},k}$ under orientation choice, root choice, and positive penalty weights.}",
        r"\label{tab:robustness-summary}",
        r"\begin{tabular}{l l r r r}",
        r"\hline",
        f"Sweep & Graph & $k$ & cases & invariant count {LATEX_NL}",
        r"\hline",
    ]
    for row in rows:
        status = "yes" if row["status"] else "FAIL"
        lines.append(f"{row['sweep']} & {latex_graph_name(row['graph'])} & {row['k']} & {row['cases']} & {row['invariant']} ({status}) {LATEX_NL}")
    lines.extend([r"\hline", r"\end{tabular}", r"\end{table}"])
    tex_path.write_text("\n".join(lines) + "\n")


def main() -> None:
    theorem_rows = generate_theorem_representative()
    write_theorem_representative(theorem_rows)

    qubo_rows = generate_qubo_structure()
    write_qubo_structure(qubo_rows)

    robustness_rows = generate_robustness_summary()
    write_robustness_summary(robustness_rows)

    snark_rows = generate_snark_benchmarks()
    write_snark_benchmarks(snark_rows)

    print(f"Wrote tables to {OUTDIR}")
    for name in [
        "theorem_representative.tex", "qubo_structure.tex",
        "robustness_summary.tex", "snark_benchmarks.tex",
        "theorem_representative.csv", "qubo_structure.csv",
        "robustness_summary.csv", "snark_benchmarks.csv",
        "theorem_representative.json", "qubo_structure.json",
        "robustness_summary.json", "snark_benchmarks.json",
    ]:
        print(" -", name)


if __name__ == "__main__":
    main()
